name: ocr_sederhana
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Plugin tambahan untuk OCR dan kamera
  google_mlkit_text_recognition: ^0.15.0
  camera: ^0.11.0
  path_provider: ^2.1.3
  path: ^1.9.0

  permission_handler: ^11.3.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
